### ISSUE TITLE
Registrieren

### ISSUE THREAD

**Issue by Felithium** [Felithium/my_cargonaut#1]
- Vorname, Nachname, Email (zweimal angeben), Passwort, Geburtstag (nur ab 18+)
- Sobald man Angebot erstellen will zusätzlich: Handynummer (unsichtbar), Bild

**Comment by Tamiira** [comment]
![wireframe17_register](https://user-images.githubusercontent.com/57072200/71835693-74cb1680-30b2-11ea-8cbe-55adb6fb03f2.png)
![wireframe07_newoffer1_marked](https://user-images.githubusercontent.com/57072200/71835838-de4b2500-30b2-11ea-98da-2117ca363215.png)
![wireframe08_newoffer2_marked](https://user-images.githubusercontent.com/57072200/71835841-e2774280-30b2-11ea-9589-1b7b3d5847f0.png)
