### ISSUE TITLE
Suche

### ISSUE THREAD

**Issue by Felithium** [Felithium/my_cargonaut#3]
- Nach Angebot
- Nach Gesuch
- Von/Bis, Datum, Fracht (Gewicht/Maße), Nach Bewertung, Anzahl verfügbare Plätze

**Comment by Tamiira** [comment]
![wireframe02_search](https://user-images.githubusercontent.com/57072200/71836753-f2902180-30b4-11ea-8dad-5533266ab619.png)
![wireframe04_searchResults1](https://user-images.githubusercontent.com/57072200/71836771-fde34d00-30b4-11ea-8ea4-a40071ce4544.png)
