### ISSUE TITLE
Profilansicht

### ISSUE THREAD

**Issue by Felithium** [Felithium/my_cargonaut#4]
- Nur für registrierte Benutzer
- Öffentlich: Vorname, Nachname (Erster Buchstabe), Bild, Alter, zusätzliche Notiz,
Bewertungen, Anzahl Fahrten(Angeboten/Gesuch),
- Erfahrung Messen an: Anzahl Mitfahrer, Anzahl Gewicht (von Elefant bis Todesstern),
Strecke, Sprachen, Raucher

**Comment by Tamiira** [comment]
![wireframe09_profile](https://user-images.githubusercontent.com/57072200/71836060-7c3eef80-30b3-11ea-86f7-1264e036e34f.png)
