### ISSUE TITLE
Benutzer-/Fahrzeugverwaltung

### ISSUE THREAD

**Issue by Felithium** [Felithium/my_cargonaut#5]
- Profil editierbar, siehe Profilansicht (Attribute)
- Fahrzeug editierbar
- Sonderfunktionen (z.B. Kühlung), Gewicht, Maße

**Comment by Tamiira** [comment]
![wireframe10_edit_profile](https://user-images.githubusercontent.com/57072200/71836083-8b25a200-30b3-11ea-8a0c-920fd16761cf.png)
![wireframe11_edit_vehicles](https://user-images.githubusercontent.com/57072200/71836089-8cef6580-30b3-11ea-8df5-f3521bef9cef.png)
