### ISSUE TITLE
Bewertung

### ISSUE THREAD

**Issue by Felithium** [Felithium/my_cargonaut#6]
- Nach erfolgter Fahrt
- 5-Sterne-Skala (5 Sterne entsprechen der besten, 1 Stern der schlechtesten
Bewertung)
- Nach einer Fahrt werden alle Teilnehmer aufgefordert, sich gegenseitig zu bewerten.
Fahrer bewerten dabei ihre Mitfahrer, Mitfahrer ihre Fahrer. Bewertungen können 
nur bei Fahrten vorgenommen werden, die nicht storniert wurden. Dabei sind jeweils
drei Fragen zu beantworten:
o Bewertung der Fahrer durch die Mitfahrer
▪ War der Fahrer pünktlich? (+/- 5 Minuten)
▪ Hat sich der Fahrer an alle Abmachungen gehalten? (Treffpunkt usw.)
▪ Haben Sie sich bei der Fahrt wohl gefühlt?
▪ Ist die Fracht unbeschadet angekommen?
o Bewertung der Mitfahrer durch die Fahrer
▪ War der Mitfahrer pünktlich? (+/- 5 Minuten)
▪ Hat sich der Mitfahrer an alle Abmachungen gehalten? (Treffpunkt
usw.)
▪ Haben Sie den Mitfahrer gerne mitgenommen?
o Bewertung erst sichtbar, wenn alle Beteiligten bewertet haben

**Comment by Tamiira** [comment]
![wireframe16_rating](https://user-images.githubusercontent.com/57072200/71836168-ccb64d00-30b3-11ea-9176-edd0d857ba0a.png)
