### ISSUE TITLE
Angebot/Gesuch erstellen

### ISSUE THREAD

**Issue by Felithium** [Felithium/my_cargonaut#7]
- Ablauf:
1. Feste Zusage per Button auf der Plattform inkl. Zahlungsvorgang
2. Möglichkeit der Kommunikation per Telefon/Nachrichten
3. Nach der Fahrt (Bewertung des Fahrers/Mitfahrers)
4. Speichern aller Daten für statistische Zwecke
- Von/Bis/Zwischenziele, Zeitraum, Fahrzeug/Anhänger auswählen
- Verfügbar: Gewicht/Maß/Sitzplätze, Preis fest pro Person/Fracht verhandelbar
- Einschränkungen: Nehme keine Tiere mit, Nichtraucher
- Info/Hinweis: höre gerne Musik, Unterhalte mich gern, richte mich nach Mitfahrern
- Informationen über Fahrzeug/Anhänger

**Comment by Tamiira** [comment]
![wireframe05_searchresultdetails1](https://user-images.githubusercontent.com/57072200/71836274-02f3cc80-30b4-11ea-8062-cd80a0987156.png)
![wireframe06_searchresultdetails2](https://user-images.githubusercontent.com/57072200/71836275-02f3cc80-30b4-11ea-9fb6-2445dc7982f5.png)
![wireframe12_bookings](https://user-images.githubusercontent.com/57072200/71836297-0f782500-30b4-11ea-95df-b9ef6c041eb0.png)
![wireframe14_bookingdetails](https://user-images.githubusercontent.com/57072200/71836383-27e83f80-30b4-11ea-8551-44f587abe5da.png)
![wireframe13_chat](https://user-images.githubusercontent.com/57072200/71836291-0b4c0780-30b4-11ea-9aef-44e594ae6da1.png)
