### ISSUE TITLE
Preisgestaltung

### ISSUE THREAD

**Issue by Felithium** [Felithium/my_cargonaut#8]
- Angebote und Gesuche sind kostenlos, aber sobald eine Fahrt zustande kommt, muss
der Mitfahrer an die Plattform den festgelegten Preis zahlen. Auszahlung erfolgt nach
Abschluss der Fahrt abzüglich unserer Vermittlungsgebühr.
- Festpreis: Angebot/Gesuch z.B. 5€
- Variabler Preis: Angebot/Gesuch abhängig von Personenzahl/Gewicht (verfügbar)

**Comment by Tamiira** [comment]
![wireframe07_newoffer1_markedPrice](https://user-images.githubusercontent.com/57072200/71836713-e0ae7e80-30b4-11ea-9b7d-804b94f7e14a.png)
![wireframe08_newoffer2_markedPrice](https://user-images.githubusercontent.com/57072200/71836723-e5733280-30b4-11ea-9cd4-a544caf46caa.png)
